### ISSUE TITLE
Lesson 5 missing

### ISSUE THREAD

**Issue by huguesfontenelle** [katyhuff/python-testing#4]
Lesson 5 "Running Tests with pytest" is absent from this repo.

**Comment by franktoffel** [comment]
I was checking the lesson and found out same error.

**Comment by katyhuff** [comment]
fixed, at long last. I do intend to replace this with pytest rather than nosetests. only very minor changes needed, and they've already been made, but I need to find that md file so that the right people get credit (matt davis). This was done for the scipy workshop, but I failed to move it over. will do that tonight.

**Comment by katyhuff** [comment]
ok, actually fixed now.

**Comment by franktoffel** [comment]
thanks!

**Comment by huguesfontenelle** [comment]
Great, good job!
